config/routes.rb
Endpoints::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: "users/registrations" }

  root 'endpoints#index'

  resources :endpoints
  get '/about' => "endpoints#about"
  get '/account/endpoints' => "endpoints#index", type: :account
  get '/widgets/:id' => 'endpoints#show', type: :widget, as: :widget
  post '/proxy' => 'proxy#go'
  get 'playground' => 'endpoints#playground'
  match 'playground/smartthings' => 'services#smartthings', via: [:get, :post]

  get '/playground/add/:x/:y' => 'services#add'

end

app/models/endpoint.rb
class Endpoint < ActiveRecord::Base
	validates_presence_of :name, :url, :method, :description
	before_create { |e| e.public_id = Endpoint.generate_public_id }
	HTTP_VERB = %w(GET POST PUT)
	#scope :published, where(published: true)
	scope :published, -> { where(published: true) }
	paginates_per 10
	belongs_to :user

	def self.generate_public_id(length = 10)
		chars = ('a'..'z').to_a + ('A'..'Z').to_a + ('1'..'9').to_a
    	[('A'..'Z').to_a[rand(26)], Array.new(length-1) { chars[rand(chars.size)] }.join].join
	end

	def post?
		method == "POST"
	end

	def get? 
		method == "GET"
	end
	
	def belongs_to? u
		user_id.to_i == u.id.to_i
	end

	def to_param
		public_id
	end
	
end

app/models/settings.rb
class Settings < RailsSettings::CachedSettings
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable,
   	  	 :omniauthable, :omniauth_providers => [:google_oauth2]

  validates_presence_of :firstname, :lastname
  
  has_many :endpoints
    
  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    logger.debug data
    user = User.where(:email => data["email"]).first

    unless user
      user = User.create(firstname: data["first_name"], lastname: data["last_name"], email: data["email"], password: Devise.friendly_token[0,20])
    end
    user
  end

  def fullname
    [firstname, lastname].join(" ")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/endpoints_controller.rb
class EndpointsController < ApplicationController

	before_action :authenticate_user!, except: [:show, :index, :about]
	helper_method :show_all_endpoints?

	def new
		@endpoint = Endpoint.new
	end

	def show
		@endpoint = Endpoint.find_by_public_id(params[:id])
		if params[:type] == :widget
		 	render layout: 'widget' 
		 	# response.headers['X-Frame-Options'] = 'ALLOW-FROM http://open.iot-butler.eu'
		 	# response.headers["X-FRAME-OPTIONS"] = "ALLOW-FROM http://example.com"
		 	response.headers.delete "X-Frame-Options"
		end
		
	end

	def edit
		@endpoint = current_user.endpoints.find_by_public_id(params[:id])
	end

	def create
		@endpoint = current_user.endpoints.new endpoint_params
		if @endpoint.save
			redirect_to edit_endpoint_path(@endpoint), notice: "Endpoint created."
		else
			render :new
		end
	end

	def update
		@endpoint = current_user.endpoints.find_by_public_id(params[:id])
		if @endpoint.update_attributes endpoint_params
			redirect_to edit_endpoint_path(@endpoint), notice: "Endpoint updated."
		else
			render :edit
		end
		
	end

	def endpoint_params
  		params.require(:endpoint).permit(:name, :description, :url, :method, :parameters, :headers, :show_body, :post_body, :published)

  	end

  	def index
  		@show_all = params[:type] != :account
  		@endpoints =  @show_all == true ? Endpoint.published.order(:name).page(params[:page]) : current_user.endpoints.order(:name).page(params[:page])
  		unless params[:q].blank?
  			@endpoints = @endpoints.where("name LIKE :query OR description LIKE :query", query: "%#{params[:q]}%")
  		end
  	end

  	def destroy
  		@endpoint = current_user.endpoints.find_by_public_id params[:id]
  		@endpoint.destroy
  		redirect_to account_endpoints_path, notice: "The endpoint entry has been successfully deleted."
	end

	def show_all_endpoints?
		@show_all
	end

end

app/controllers/proxy_controller.rb
class ProxyController < ApplicationController
	include HTTParty
	debug_output $stderr
	
	def go
		method = params[:method]
		url = params[:url]
		headers = params[:headers]

		response = ProxyController.proxy(url, method, params[:parameters], params[:postBody], headers)
	
		respond_to do |format|
  		 format.json { render json: response.to_json }
		end
	end

	def self.proxy(url, method, parameters, body, headers)
		#options = { :body => parameters.to_json, :format => "json", :headers => headers}
		options = { :body => body, :format => "json", :headers => headers}
		HTTParty.send(method.downcase, *[url, options])
	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

    def sign_up_params
        params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation, :current_password)
    end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

	skip_before_action :verify_authenticity_token

	def add
		render json: {x: params[:x].to_i, y: params[:y].to_i, sum: (params[:x].to_i + params[:y].to_i).to_i}
	end

	# tmp to test notifications from the SmartThings cloud engine
	def smartthings
		render text: "ok :-)"
	end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
	
	def google_oauth2
	    # You need to implement the method below in your model (e.g. app/models/user.rb)
	    @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)

	    if @user.persisted?
	      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
	      sign_in_and_redirect @user, :event => :authentication
	    else
	      session["devise.google_data"] = request.env["omniauth.auth"]
	      redirect_to new_user_registration_url
	    end
	end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

private

def sign_up_params
params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation)
end

def account_update_params
params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation, :current_password)
end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# def input_wrapper name
	# 	content_tag(:div, class: "form-group") do 
	# 		concat(content_tag(:label, class: "col-sm-2.control-label") do
	# 			name
	# 		end)
	# 		concat(yield)
	# 	end

	# end

	def input_wrapper name, required, help_text = ""
		content_tag(:div, class: "form-group #{'required' if required == true}") do 
			concat(content_tag(:label, class: "col-sm-2 control-label") do
				name
			end)
			concat(content_tag(:div, class: "col-sm-10") do
				yield
				concat(content_tag(:p, class: "help-block") do
					help_text
			end) unless help_text.blank?

			end)
		end

	end

	def icon(name, text = "")
    	content_tag(:span, class: "glyphicon glyphicon-#{name}") {} + "&nbsp;#{text}".html_safe
	end

	def title t, hide_h1 = false
	    content_for :title, t
	    content_tag(:h1, t) unless hide_h1
  	end

  def bootstrap_class_for(flash_type)
    case flash_type
      when "success"
        "alert-success"   # Green
      when "error"
        "alert-danger"    # Red
      when "alert"
        "alert-warning"   # Yellow
      when "notice"
        "alert-info"      # Blue
      else
        flash_type.to_s
    end
  end

end

app/helpers/devise_helper.rb
module DeviseHelper

  # from http://www.jacopretorius.net/2014/03/adding-custom-fields-to-your-devise-user-model-in-rails-4.html
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

	html = <<-HTML
    	<div class="alert alert-danger">
      	<strong>#{sentence}</strong>
      	<ul>
       	 #{messages}
      	</ul>
    	</div>
	HTML


    html.html_safe
  end
end

app/helpers/endpoints_helper.rb
module EndpointsHelper

	def editable?(endpoint)
		user_signed_in? && !endpoint.new_record? && endpoint.belongs_to?(current_user)
	end

	def css_method_class(endpoint)
		endpoint.get? ? 'info' : 'success'
	end

end

app/views/endpoints/_code.html.haml
%textarea{rows: 2}
	%iframe{width: "800", height: "500", src: widget_url(endpoint.public_id), frameborder: "0", allowfullscreen: true}

app/views/endpoints/_form.html.haml
= form_for @endpoint, html: {class: "form-horizontal", role:"form"} do |f| 

    - if @endpoint.errors.any?
        .alert.alert-danger
            %p The endpoint has not been saved. The following errors have been detected:
            %ul.errors
                - @endpoint.errors.full_messages.each do |msg|
                    %li= msg 
  
    = input_wrapper "Name", true do
        = f.text_field :name, placeholder: "Name of the endpoint", class: "form-control"
    = input_wrapper "Description", true do
        = f.text_area :description, as: "text", class: "form-control wysihtml5", rows: 4
    = input_wrapper "HTTP Verb", true do
        = f.select :method, Endpoint::HTTP_VERB, {}, class: "form-control"
    = input_wrapper "Published ?", false, "When this box is checked, the endpoint is made public." do
        = f.check_box :published

    #show-body-wrapper{style: "#{'display: none;' unless @endpoint.post? }"}
        = input_wrapper "Show body field", false do
            = f.check_box :show_body
    = input_wrapper "URL", true, "Wrap URL parameters in braces. Example: http://www.example.com/api/{x}/get" do    
        = f.text_field :url, class: "form-control input-xlarge"
    = f.hidden_field :parameters
    = f.hidden_field :headers
    = f.hidden_field :post_body
    

    #params
        %h3 Parameters
        %table.table.table-striped.table-condensed.operation-params
            %tr.muted
                %th Name
                %th Value
                %th Description
                %th Type
                %th
        %button.btn{type: "button", onclick: "addParameter()"} 
            = icon "plus", "Add parameter"


    #headers
        %h3 HTTP Headers
        %table.table.table-striped.table-condensed.operation-headers
            %tr.muted
                %th Name
                %th Value
                %th Description
                %th
        %button.btn{type:"button", onclick: "addHeader()"}
            = icon "plus", "Add a HTTP header"

    = f.button "#{@endpoint.new_record? ? 'Create this endpoint' : 'Update'}", :class =>"btn btn-primary", id: "submit"

app/views/endpoints/_js.html.haml
#post-body
    %h3 Body
    %textarea#post-body-content.form-control= @endpoint.post_body


= javascript_tag do 

    var endpoint = { parameters: '#{@endpoint.parameters.nil? ? "" : @endpoint.parameters.html_safe }', headers: '#{@endpoint.headers.nil? ? "": @endpoint.headers.html_safe}' };

    = render partial: "template", formats: "js"

    - unless @endpoint.blank?
        endpoint['id'] = "#{@endpoint.id}";
        endpoint['name'] =  "#{@endpoint.name}";
        endpoint['description'] = "#{@endpoint.description.blank? ? '' : CGI.escapeHTML(@endpoint.description)}";
        $(document).ready(function(){ $("#description").text(endpoint['description']); });
        endpoint['url'] =  "#{@endpoint.url}";
        endpoint['method'] =  "#{@endpoint.method}";
        var params = parseJSON(endpoint.parameters);
        var headers = parseJSON(endpoint.headers);
        - if controller.action_name != 'show'
            document.forms[document.forms.length-1].onsubmit = submitService;
            document.getElementById('endpoint_url').oninput = input;
            updateParams(document.getElementById('endpoint_url').value);
            var i = 0, j = headers.length;
            var line = document.querySelector('#headers table tr');
            for(;i<j;i++){line.parentNode.appendChild(createHeaderElement(headers[i]));}

        // model is used to provide the data to build corresponding HTML
        :plain
            var model = {
                name: 'API',
                version: 0.1,
                library_id: endpoint.id, // useless
                responseType: 'json',
                services: [
                    {
                        id: endpoint.id,
                        name: endpoint.name,
                        description: endpoint.description,
                        url: endpoint.url,
                        method: endpoint.method,
                        headers: parseJSON(endpoint.headers),
                        params: parseJSON(endpoint.parameters),
                        editable: false, // useless
                        deletable: false // useless
                    },
                ]
            };
        
            

    

app/views/endpoints/_template.js.erb
// Templates used for HTML elements
var Templates = {

    url: '\
    <a data-parent="#api" href="#{href}"">\
        {url}\
    </a>',

    name: '{name}',

    description: '{description}',

    method: '<span class="method label label-primary label-{methodClass}">{method}</span>',

    head: '\
    <div class="page-header">\
        <h1>{name} <small id="description"></small><%= "<span class=\"options\">(or #{link_to("edit it", edit_endpoint_path(@endpoint))})</span>".html_safe if editable?(@endpoint)%></h1>\
    </div>\
    <div class="endpoint">\
        <div class="">\
            <h5>\
                {method}\
                {url}\
            </h5>\
            <% unless @endpoint.new_record? -%>
            <%= link_to icon("export", "Export code"), "", :class => "btn btn-primary btn-xs btn-export", "data-endpoint-id" => @endpoint.public_id %>\
            <br/>\
            <code id="export-<%= @endpoint.public_id %>">\
            <textarea style="clear: both;"><iframe allowfullscreen frameborder="0" height="500" src="<%= widget_url(@endpoint.public_id) %>" width="800"></iframe></textarea>\
            </code>\
            <% end -%>
        </div>\
    </div>\
    ',

    body: '\
    <div id="{id}" data-service="{dataService}" class="">\
        <div class="">\
            <form id="request-sender" onsubmit="API.submit(event)">\
                {params}\
                {headers}\
                <button class="btn" type="submit"><i class="glyphicon glyphicon-play"></i> Test</button>\
                {editbutton}\
                {deletebutton}\
            </form>\
            <ul class="response nav nav-tabs" onsubmit="API.submit(event)">\
                <li class="active">\
                    <a data-toggle="tab" href="">Response</a>\
                </li>\
            </ul>\
            <div class="tab_content">\
                <div class="response json">\
                    <iframe style="border:none;width:100%;"></iframe>\
                </div>\
            </div>\
        </div>\
    </div>\
    ',

    param: '\
    <tr>\
        <td>\
            {name}\
        </td>\
        <td>\
            <input type="text" class="form-control" value="{value}" required />\
        </td>\
        <td>\
            {description}\
        </td>\
        <td>\
            {type}\
        </td>\
    </tr>\
    ',

    params: '\
    <div id="params">\
        <h3>Parameters</h3>\
        <table class="table table-striped table-condensed operation-params">\
            <tr class="muted">\
                <th>Parameter</th>\
                <th>Value</th>\
                <th>Description</th>\
                <th>Type</th>\
            </tr>\
            {params}\
        </table>\
    </div>\
    ',

    header: '\
    <tr>\
        <td>\
            {name}\
        </td>\
        <td>\
            <input type="text" class="form-control" value="{value}" required />\
        </td>\
        <td>\
            {description}\
        </td>\
    </tr>\
    ',

    headers: '\
    <div id="request-location"></div>\
    <h3>Headers</h3>\
    <table class="table table-striped table-condensed operation-headers">\
        <tr class="muted">\
            <th>Header</th>\
            <th>Value</th>\
            <th>Description</th>\
        </tr>\
        {headers}\
    </table>\
    ',

    service: '\
    <div class="accordion-group">\
        {head}\
        {body}\
    </div>\
    ',

    api: '\
    <div class="accordion" id="api">\
        {services}\
    </div>\
    '
};

app/views/endpoints/about.html.erb
<%= title "About the Endpoints app" %>

<p>Endpoints is a webapp that aims at documenting web services. It has been developed in the context of the <%= link_to "BUTLER project", "http://www.iot-butler.eu", target: "_blank" %> in order to well document IoT web services (e.g. endpoints).</p>

<p>The Endpoints app is now part of the <%= link_to "Open Platforms", "http://www.open-platforms.eu", target: "_blank" %> initiative and is documented here: <%= link_to "http://open-platforms.eu/library/endpoints", "http://www.open-platforms.eu", target: "_blank" %>.</p>

<h4>Contact</h4>

For any question, please contact Fabrice Clari (f.clari@inno-group.com).

app/views/endpoints/edit.html.haml
%h1= "Edit an endpoint <span class='options'>(or #{link_to 'use it', @endpoint}, or #{link_to 'export it', '', class: 'btn-export', 'data-endpoint-id' => @endpoint.public_id})</span>".html_safe

.endpoint
	%code{id: "export-#{@endpoint.public_id}"}
		= render partial: "code", locals: {endpoint: @endpoint}


= render 'form'

= render 'js'

app/views/endpoints/index.html.haml
= title show_all_endpoints? ? "Endpoints" : "My endpoints"

- if @endpoints.blank?
    .alert.alert-info= "No endpoint exists here yet. #{ link_to "Create a new one", new_endpoint_path } ?".html_safe

- @endpoints.all.each do |endpoint|

    .endpoint
        %h3

            = endpoint.name
        %p= endpoint.description

        %p
            = link_to icon("wrench", "Use"), endpoint, class: "btn btn-primary btn-sm"
            =# link_to icon("link", "Widget URL"), widget_path(endpoint.public_id), class: "btn btn-primary btn-sm"
            = link_to icon("export", "Export code"), "", :class => "btn btn-primary btn-sm btn-export", "data-endpoint-id" => endpoint.id
            - if user_signed_in? && endpoint.belongs_to?(current_user)
                = link_to icon("edit", "Edit"), edit_endpoint_path(endpoint), class: "btn btn-warning btn-sm"
                = link_to icon("remove", "Delete"), endpoint, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm"
        %p
            %span.method.label.label-primary{class: "label-#{css_method_class(endpoint)}"}= endpoint.method 
            - if !show_all_endpoints?
                - if endpoint.published?
                    %span.label.label-success This endpoint is published.
                - else 
                    %span.label.label-warning This endpoint is not published.
            - else
                %span.label.label-default= "Published by #{endpoint.user.fullname}."
        %code{id: "export-#{endpoint.id}"}
            = render partial: "code", locals: {endpoint: endpoint}

        %hr 

= paginate @endpoints

app/views/endpoints/new.html.haml
= title "Add a new endpoint"

= render 'form'
= render 'js'

app/views/endpoints/playground.html.erb
<iframe allowfullscreen frameborder='0' height='315' src='http://localhost:3000/widgets/kEXAzpvDzE' width='560'></iframe>

app/views/endpoints/show.html.haml
.row-fluid#services

= render 'js'

= javascript_tag do 
	document.getElementById('services').innerHTML = HTMLView.draw();

app/views/layouts/_ga.html.haml
- unless Settings.google_analytics_tracking_code.blank?
	= Settings.google_analytics_tracking_code.html_safe

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset='utf-8'>
    <meta content='IE=Edge,chrome=1' http-equiv='X-UA-Compatible'>
    <meta content='width=device-width, initial-scale=1.0' name='viewport'>
  	<%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
  	<%= csrf_meta_tags %>
    <title><%= content_for?(:title) ? yield(:title) : "Endpoints" %></title>
  </head>
  <body>
    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= root_path %>">Endpoints</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to icon("th", "Show all"), endpoints_path %></a></li>      
            <% if user_signed_in? %>
              <li><%= link_to icon("th-large", "My endpoints"), account_endpoints_path %></a></li>      
            <% end %>
            <li><%= link_to icon("plus", "Add new"), new_endpoint_path %></a></li>
            <li><%= link_to icon("info-sign", "About"), "/about" %></li>
            <li class="pull-right">
              <%= render "/users/menu" %>
            </li>
          </ul>

          <form class="navbar-form navbar-left" role="search" action="<%= request.path %>" method="get">
            <div class="form-group">
              <input name="q" type="text" class="form-control" placeholder="Keywords" value="<%= params[:q] %>">
            </div>
            <button type="submit" class="btn btn-default">Search</button>
          </form>

        </div><!--/.nav-collapse -->
      </div>
    </div>
  
  <a href="https://github.com/butler-fp7/endpoints"><img style="z-index: 99999; position: absolute; top: 0; right: 0; border: 0;" src="https://camo.githubusercontent.com/a6677b08c955af8400f44c6298f40e7d19cc5b2d/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f677261795f3664366436642e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png"></a>
  
    <!-- main content goes here -->
    <div class='container'>
      <% flash.each do |type, message| %>
        <div class="alert <%= bootstrap_class_for(type) %> fade in">
          <button class="close" data-dismiss="alert">×</button>
          <%= message %>
        </div>
      <% end %>

    	<%= yield %>

    </div>
  
  <%= render partial: "layouts/ga" %>
  </body>
  
</html>

app/views/layouts/widget.html.erb
<!DOCTYPE html>
<html lang='en'>
  <head>
    <title>Endpoints</title>
    <meta charset='utf-8'>
    <meta content='IE=Edge,chrome=1' http-equiv='X-UA-Compatible'>
    <meta content='width=device-width, initial-scale=1.0' name='viewport'>
  	<%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <title><%= content_for?(:title) ? yield(:title) : "Endpoints" %></title>
    <style>
      body {
        margin-top: 0px;
        padding-top: 0px;
      }
    </style>
  </head>
  <body>
 
    <!-- main content goes here -->
    <div class='container'>
    	<%= yield %>
    </div>
  

  <%= render partial: "layouts/ga" %>
  </body>
  
</html>

app/views/users/_fields.html.haml
= input_wrapper "Firstname", true do
    = f.text_field :firstname, autofocus: true, class: "form-control"

= input_wrapper "Lastname", true do
    = f.text_field :lastname, autofocus: true, class: "form-control"

= input_wrapper "email", true do
    = f.email_field :email, autofocus: true, class: "form-control"

= input_wrapper "Password", true do
    = f.password_field :password, autocomplete: "off", class: "form-control"
    - unless resource.new_record?
        %p.help-block Leave blank if you don't want to change it.

= input_wrapper "Password confirmation", true do
    = f.password_field :password_confirmation, autocomplete: "off", class: "form-control"

app/views/users/_menu.html.haml
%a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
    - if !user_signed_in?
        = icon("log-in", "Sign in")
    - else
        = icon("home", "My account")
    %ul.dropdown-menu
        - if user_signed_in?
            %li= link_to "My profile", edit_user_registration_path
            %li.divider
            %li= link_to icon("log-out", "Log out"), destroy_user_session_path, :method => :delete           
        -else
            %li=link_to "Sign in", new_user_session_path
            %li=link_to "Sign up", new_user_registration_path